spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
#            request-interceptors:
#              - com.zzc.order.interceptor.XTokenRequestInterceptor
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
      web-context-unify: false
#            retryer: com.zzc.order.retryer


feign:
  sentinel:
    enabled: true